# Generated by Django 4.1.7 on 2023-06-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompleteSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='products')),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAddons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SingleMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='products')),
                ('date', models.DateField(auto_now=True)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
