# Generated by Django 4.1.7 on 2023-06-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_completeset_serviceaddons_singlematerial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceaddons',
            name='service',
        ),
        migrations.AddField(
            model_name='serviceaddons',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='serviceaddons',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceaddons',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='serviceaddons',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceaddons',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceaddons',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='completeset',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='singlematerial',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
    ]
