# Generated by Django 4.1.7 on 2023-06-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_serviceaddons_service_serviceaddons_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='brand',
        ),
    ]
