# Generated by Django 4.1.7 on 2023-07-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_completeset_options_alter_fournisseur_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9),
        ),
    ]
