# Generated by Django 4.2.3 on 2023-07-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_management', '0002_alter_email_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='date',
        ),
    ]
